# Generated by Django 4.0.3 on 2022-03-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.track'),
        ),
    ]
