# Generated by Django 4.0.3 on 2022-03-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_st_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='trtack_name',
            new_name='track_name',
        ),
    ]
